language: csharp
matrix:
  include:
    - mono: 2.10.8
      env: MONO_V=MONO2
      solution: src/NLog.mono2.sln
    - mono: latest
      env: MONO_V=MONO4
      solution: src/NLog.mono4.sln

  fast_finish: true

before_script: chmod ugo+x build-mono.sh
script: ./build-mono.sh

