version: 4.4.0-Alpha{build}
clone_folder: c:\projects\nlog
branches:
  only:
  - coreCLR
build_script:
  - build.cmd -Configuration Debug
before_test:
  - tests\CreateTestUsers.cmd
after_test:
  - tests\DeleteTestUsers.cmd

artifacts:
  - path: '**\*.nupkg'
deploy: off
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config
